name: 'Node Setup'
description: 'Initial setup for node'

runs:
  using: 'composite'
  steps:
    - uses: ./.github/workflows/actions/job-setup

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        cache: 'yarn'
        node-version: '18'
        registry-url: 'https://registry.npmjs.org'

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Yarn install
      run: yarn install --frozen-lockfile
      shell: bash
